---

- name: remove resolvconf
  tags:
    - resolved
    - package
  package:
    state: absent
    purge: yes
    name: 
      - resolvconf
      - openresolv
  when:
    - ansible_os_family == 'Debian'

- name: install libnss-resolve
  tags:
    - resolved
    - package
  package:
    name: libnss-resolve
  when:
    - ansible_os_family == 'Debian'

- name: install systemd-resolved
  tags:
    - resolved
    - package
  package:
    name: systemd-resolved
  when:
    - ansible_os_family == 'Debian'
    - ansible_lsb.major_release | int >= 12


- name: add default config
  tags:
    - resolved
    - config
  template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf
  notify: restart systemd-resolved

- name: ensure the /etc/systemd/resolved.conf.d/ directory exists
  file:
    state: directory
    path: "/etc/systemd/resolved.conf.d/"
  tags:
    - resolved
    - config

- name: add specific configuration files
  tags:
    - resolved
    - config
  ansible.builtin.template:
    src: resolved.conf.d/resolved.conf.j2
    dest: "/etc/systemd/resolved.conf.d/{{ item.key }}"
    owner: root
    group: root
    mode: 0644
  with_dict: "{{ resolved_conf_d_configs }}"
  notify: restart systemd-resolved

- name: check resolvectl
  tags:
    - resolved
    - config
  stat:
    path: /usr/bin/resolvectl
  register: ctl_stat

- name: emulate resolvconf
  tags:
    - resolved
    - config
  file:
    src: /usr/bin/resolvectl
    dest: /sbin/resolvconf
    state: link
  when: ctl_stat.stat.exists is defined and ctl_stat.stat.exists

- name: dhclient hook
  tags:
    - hook
    - resolved
    - config
  copy:
    src: resolvconf
    dest: /etc/dhcp/dhclient-enter-hooks.d/
  when: ctl_stat.stat.exists is defined and ctl_stat.stat.exists

- name: service
  tags:
    - resolved
    - service
  systemd:
    name: systemd-resolved
    masked: no
    enabled: yes
    state: started
  notify: use systemd-resolved

- name: stub /etc/resolv.conf
  tags:
  - resolved
  file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: true
